### ISSUE TITLE
结构体中的字段如果是int类型的，就不能拼接了？

### ISSUE THREAD

**Issue by savico-swee** [yuchenfw/go-join#1]
dataString, _ := gojoin.Join(&People{
		Id:   1,
		Name: "小明",
		Age:  1,
	}, gojoin.Options{
		Sep:        "&",
		KVSep:      "=",
		Order:      gojoin.ASCII,
		//ExceptKeys: []string{"sign", "sign_type"},
		Unwrap:     true,
		StructTag:  "json",
	})

	fmt.Println("dataString:", dataString)

output: dataString: &&name=小明

**Comment by savico-swee** [comment]
这个得自己转一下格式对吧，都转成字符串的

**Comment by yuchenfw** [comment]
已支持非string类型join
